var DB3 = {
	"spirits" :
	    [{
	    	/* This Database is inteded to be used as a smaller version of beverages.js with selected beverages 
	    	from the categories Ljusa Lagers, Porters & Stouts, Ales och Mörka Lagers*/
	    	//LIGHT LAGERS
	    	"nr": "1177703",
            "artikelid": "676236",
            "varnummer": "11777",
            "namn": "Samichlaus Helles",
            "namn2": "",
            "prisinklmoms": "35.80",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-12-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "\u00c3\u2013sterrike",
            "producent": "Brauerei Schloss Eggenberger",
            "leverantor": "World Beer Trading KB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "14%",
            "modul": "T5",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
		}, {
			"nr": "120003",
            "artikelid": "186120",
            "varnummer": "1200",
            "namn": "Mariestads Export",
            "namn2": "",
            "prisinklmoms": "13.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Dalarnas l\u00c3\u00a4n, Ludvika kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Spendrups",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.3%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "120515",
            "artikelid": "676826",
            "varnummer": "1205",
            "namn": "Carling",
            "namn2": "Lager",
            "prisinklmoms": "11.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-10-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ljus lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Molson Coors Brewing Company",
            "leverantor": "Bibendum",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
			"nr": "120615",
            "artikelid": "670003",
            "varnummer": "1206",
            "namn": "Steinlager Pure",
            "namn2": "",
            "prisinklmoms": "12.50",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-10-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ljus lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Nya Zeeland",
            "producent": "Lion Beer, Spirits & Wine NZ",
            "leverantor": "Arvid Nordquist Vin och Sprith",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "FSN",
            "ekologisk": "0",
            "koscher": "0"
		}, {
			"nr": "121503",
            "artikelid": "693300",
            "varnummer": "1215",
            "namn": "Solsidan",
            "namn2": "Low Carb Premium Dry",
            "prisinklmoms": "19.70",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-08-27",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Solsidans Bryggeri AB",
            "leverantor": "Solsidans Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
			"nr": "122601",
            "artikelid": "7098",
            "varnummer": "1226",
            "namn": "Norrlands Guld",
            "namn2": "Dynamit",
            "prisinklmoms": "14.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1995-01-30",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Dalarnas l\u00c3\u00a4n, Ludvika kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Spendrups",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "7%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0" 
		}, {
			//PORTERS & STOUTS
            "nr": "126015",
            "artikelid": "507849",
            "varnummer": "1260",
            "namn": "Guinness",
            "namn2": "Draught",
            "prisinklmoms": "20.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-09-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Porter och Stout",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Irland",
            "producent": "Guinness",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.2%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "135503",
            "artikelid": "44347",
            "varnummer": "1355",
            "namn": "Slottsk\u00c3\u00a4llans Imperial Stout",
            "namn2": "",
            "prisinklmoms": "28.70",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2003-12-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Porter och Stout",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Uppsala l\u00c3\u00a4n, Uppsala kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Gamla Slottsk\u00c3\u00a4llans Bryggeri",
            "leverantor": "Gamla Slottsk\u00c3\u00a4llans Bryggeri ",
            "argang": "2011",
            "provadargang": "2011",
            "alkoholhalt": "9%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "146103",
            "artikelid": "615558",
            "varnummer": "1461",
            "namn": "S:t Eriks Porter",
            "namn2": "",
            "prisinklmoms": "19.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-03-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Porter och Stout",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Stockholms l\u00c3\u00a4n, Sigtuna kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "S:t Eriks Bryggeri",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.9%",
            "modul": "T2",
            "sortiment": "TST",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "147301",
            "artikelid": "341829",
            "varnummer": "1473",
            "namn": "Nils Oscar",
            "namn2": "R\u00c3\u00b6kporter",
            "prisinklmoms": "27.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2008-10-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Porter och Stout",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "S\u00c3\u00b6dermanlands l\u00c3\u00a4n, Nyk\u00c3\u00b6pings kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Nils Oscar Company",
            "leverantor": "The Nils Oscar Company AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.9%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "149703",
            "artikelid": "403058",
            "varnummer": "1497",
            "namn": "Carnegie Porter",
            "namn2": "",
            "prisinklmoms": "15.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2009-10-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Porter och Stout",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Hallands l\u00c3\u00a4n, Falkenbergs kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Carlsberg Sverige AB",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "2014",
            "provadargang": "2014",
            "alkoholhalt": "5.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "155803",
            "artikelid": "608280",
            "varnummer": "1558",
            "namn": "BrewDog Tokyo",
            "namn2": "",
            "prisinklmoms": "94.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-10-04",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Porter och Stout",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Storbritannien",
            "producent": "BrewDog",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "18.2%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
			// ALES //
            "nr": "156203",
            "artikelid": "434998",
            "varnummer": "1562",
            "namn": "Belhaven",
            "namn2": "Wee Heavy",
            "prisinklmoms": "16.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2010-03-24",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skottland",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Belhaven Brewery",
            "leverantor": "TOMP Beer Wine & Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "6.5%",
            "modul": "T9",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "157612",
            "artikelid": "509166",
            "varnummer": "1576",
            "namn": "Abbot Ale",
            "namn2": "",
            "prisinklmoms": "17.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-11-22",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "England",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Greene King",
            "leverantor": "TOMP Beer Wine & Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "157701",
            "artikelid": "370616",
            "varnummer": "1577",
            "namn": "St Peter's",
            "namn2": "G-Free Ale",
            "prisinklmoms": "36.30",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2009-04-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "England",
            "ursprunglandnamn": "Storbritannien",
            "producent": "St Peter's Brewery",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.2%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "158701",
            "artikelid": "631772",
            "varnummer": "1587",
            "namn": "Brakspear Triple",
            "namn2": "",
            "prisinklmoms": "29.50",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-04-02",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "England",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Brakspear Brewing",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "7.2%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "158803",
            "artikelid": "338628",
            "varnummer": "1588",
            "namn": "Brother Thelonious",
            "namn2": "",
            "prisinklmoms": "32.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2008-10-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "North Coast Brewing Company",
            "leverantor": "Great Brands AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "9.4%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "159103",
            "artikelid": "584799",
            "varnummer": "1591",
            "namn": "Brewdog Hardcore IPA",
            "namn2": "",
            "prisinklmoms": "28.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-05-30",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skottland",
            "ursprunglandnamn": "Storbritannien",
            "producent": "BrewDog",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "9.2%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
			// MÖRK LAGER
            "nr": "1101101",
            "artikelid": "765531",
            "varnummer": "11011",
            "namn": "Ayinger",
            "namn2": "Winter-Bock",
            "prisinklmoms": "30.40",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-11-15",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Tyskland",
            "producent": "Brauerei Aying",
            "leverantor": "Brill & Co AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "6.7%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "1104203",
            "artikelid": "828794",
            "varnummer": "11042",
            "namn": "Caspers Schwarz",
            "namn2": "S:t Eriks Bryggeri",
            "prisinklmoms": "19.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-05-02",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "S:t Eriks Bryggeri",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.1%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "1105303",
            "artikelid": "723445",
            "varnummer": "11053",
            "namn": "Uinta Baba Black Lager",
            "namn2": "",
            "prisinklmoms": "27.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Uinta Brewing Company",
            "leverantor": "AB Wicked Wine Sweden",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4%",
            "modul": "T6",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "1125303",
            "artikelid": "665350",
            "varnummer": "11253",
            "namn": "S:t Eriks",
            "namn2": "Oktoberfest",
            "prisinklmoms": "16.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-09-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "S:t Eriks Bryggeri",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.3%",
            "modul": "T9",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "1128603",
            "artikelid": "665237",
            "varnummer": "11286",
            "namn": "FrEQuency",
            "namn2": "No sleep in october",
            "prisinklmoms": "19.80",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-09-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Nils Oscar Company",
            "leverantor": "Philipson S\u00c3\u00b6derberg AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "T9",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0"
		}, {
            "nr": "1130003",
            "artikelid": "766395",
            "varnummer": "11300",
            "namn": "Nils Oscar",
            "namn2": "Kalasjul\u00c3\u00b6l",
            "prisinklmoms": "19.80",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-11-15",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Nils Oscar Company",
            "leverantor": "The Nils Oscar Company AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.2%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0"
		}]
};
